server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.H2Dialect
  ai:
    openai:
      api-key: test-api-key
      chat:
        options:
          model: gpt-3.5-turbo
    anthropic:
      api-key: test-api-key
      chat:
        options:
          model: claude-3-haiku-20240307

# 로깅 설정
logging:
  level:
    com.ssafy.logoserver: DEBUG
    org.hibernate.SQL: DEBUG