server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: ${GPT_MODEL:gpt-3.5-turbo}
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        options:
          model: ${CLAUDE_MODEL:claude-3-haiku-20240307}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/loggodb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useUnicode=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    hibernate:
      ddl-auto: update # 운영 환경에서는 update로 설정하여 데이터 손실 방지
    database-platform: org.hibernate.dialect.MySQLDialect

# 로깅 설정
logging:
  level:
    root: INFO
    com.ssafy.logoserver: INFO
    org.hibernate.SQL: WARN

# Swagger 설정 - 운영 환경에서는 비활성화
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false